[phases.setup]
nixPkgs = ['python39', 'chromium']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'playwright install-deps',
    'playwright install chromium'
]

[start]
cmd = 'python backend.py'